"""Validate and assemble the review inventory. This does not assess semantic conformance."""
from pathlib import Path
import collections
import csv
import hashlib
import json
import re

base = Path(__file__).resolve().parents[1]
root = Path(__file__).resolve().parents[4]
fields = ["id", "standard", "sections", "pdf_pages", "requirement", "applicability", "status", "code", "tests", "evidence_level", "finding", "impact", "closure"]
allowed_status = {"aligned", "partial", "missing", "narrowed", "contradiction", "unverified", "out_of_scope", "ambiguous"}
allowed_app = {"profile0", "extension", "acceptance", "informative"}
allowed_evidence = {"source", "retained_test", "executed_probe", "external_gate"}
inventory = []
issues = []
anchors = 0
groups = {}
for name in ["ctvs1", "ctvs2", "wire-identity", "integration"]:
    entries = json.loads((base / f"{name}.requirements.json").read_text())
    groups[name] = len(entries)
    for entry in entries:
        missing = set(fields) - entry.keys()
        if missing:
            issues.append(f"{entry.get('id')}: missing fields {missing}")
        if entry["status"] not in allowed_status or entry["applicability"] not in allowed_app or entry["evidence_level"] not in allowed_evidence:
            issues.append(f"{entry['id']}: invalid vocabulary")
        if not entry["pdf_pages"] or not all(isinstance(n, int) and 1 <= n <= 85 for n in entry["pdf_pages"]):
            issues.append(f"{entry['id']}: invalid combined PDF page")
        # Normalize richer test anchors while preserving each fragment's source form.
        entry = dict(entry)
        if isinstance(entry["sections"], str):
            entry["sections"] = [entry["sections"]]
        entry["tests"] = [
            f"{item['file']} ({'; '.join(item.get('names', []))})" if isinstance(item, dict) else item
            for item in entry["tests"]
        ]
        for anchor in entry["code"] + entry["tests"]:
            match = re.match(r"^([^\s:]+):(\d+)", anchor)
            if not match:
                issues.append(f"{entry['id']}: unparseable anchor {anchor}")
                continue
            filename, line = match.groups()
            target = root / filename
            if not target.is_file():
                issues.append(f"{entry['id']}: missing {filename}")
            elif not 1 <= int(line) <= len(target.read_text().splitlines()):
                issues.append(f"{entry['id']}: line outside file {anchor}")
            anchors += 1
        inventory.append(entry)

ids = [item["id"] for item in inventory]
if len(ids) != len(set(ids)):
    issues.append("Duplicate requirement IDs")
(base / "requirements.json").write_text(json.dumps(inventory, indent=2) + "\n")
with (base / "requirements.csv").open("w", newline="") as stream:
    writer = csv.DictWriter(stream, fieldnames=fields)
    writer.writeheader()
    for entry in inventory:
        writer.writerow({key: "; ".join(map(str, value)) if isinstance(value, list) else value for key, value in entry.items() if key in fields})

links = 0
for doc in base.glob("*.md"):
    body = doc.read_text()
    if "\u2014" in body:
        issues.append(f"{doc.name}: prohibited punctuation")
    for link in re.findall(r"\]\(([^)]+)\)", body):
        if link.startswith(("http:", "https:", "#")):
            continue
        filename = link.split("#", 1)[0]
        filename = re.sub(r":\d+$", "", filename).strip("<>")
        if not (doc.parent / filename).exists():
            issues.append(f"{doc.name}: broken link {link}")
        links += 1

summary = {"scope": "Review artifact integrity only, not a conformance score", "requirements": len(inventory), "groups": groups,
           "status_counts": dict(collections.Counter(item["status"] for item in inventory)),
           "checked_source_test_anchors": anchors, "checked_local_markdown_links": links, "issues": issues}
(base / "evidence/inventory-check.json").write_text(json.dumps(summary, indent=2) + "\n")
print(json.dumps(summary, indent=2))

# Preserve bindings to generated local evidence without copying large transaction artifacts.
generated = []
for path in sorted((root / "reference/artifacts/integration").rglob("*.json")):
    if any(part.startswith("review-") for part in path.parts):
        generated.append({"path": str(path.relative_to(root)), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "bytes": path.stat().st_size})
(base / "evidence/generated-artifact-manifest.json").write_text(json.dumps({"scope": "Generated local review transactions; paths may be regenerated by reruns", "files": generated}, indent=2) + "\n")

if issues:
    raise SystemExit(1)
